### ISSUE TITLE
Maybe add feature for multiple digital ocean accounts?

### ISSUE THREAD

**Issue by sblfc** [claffin/cloudproxy#21]
I'm loving this, it's perfect for what I need. Maybe a feature to consider in the future is to be able to use multiple digital ocean accounts as there's a limit of 10 for new users?

Thanks for releasing this!

**Comment by claffin** [comment]
Thanks for the feedback and glad you find it useful.

DO raise the limit to 100 without much hassle I've found and not necessarily keen the introduce this as it probably circumvents DO's TOS.

An alternative would be to run multiple instances of CloudProxy with Docker. Not terribly resource-efficient and you'd have to implement something within your application to hit the multiple APIs. 

I will leave the issue open for now in case there is a wider interest.

**Comment by sblfc** [comment]
Thank you, I didn't know it was that simple on a new account.

I run a homelab so self host so haven't used DO before.

May I ask what you said you used it for to get your account upgraded?

**Comment by claffin** [comment]
I can't exactly remember, I've had it for a while, I think DO just require a payment or two to be made on the account before they upgrade the limit. Topping up your account with credit or you can settle your bill early as well, then requesting for the limit upgrade. Though no guarantees. 

My etherium address is ``` 0x1C9cd536F189711f335Be1AAaf4E94a6F46DA17D ```. Many thanks!

**Comment by sblfc** [comment]
I'm sorry but the aws now doesnt seem to work, the VMs spin up but don't appear on the proxy list or in the UI even after 15 mins, with the console saying waiting for allication.

**Comment by claffin** [comment]
Thanks for reporting. I've found the issue and released a fix now. Please use the image  ```cloudproxy:0.3.3-beta``` or ```cloudproxy:latest``` now.

**Comment by claffin** [comment]
If you just ignore that error, it should still deploy the AWS instances successfully. It's a known issue where AWS creates the instance but doesn't allocate the IP instantly so when CloudProxy reads the response from AWS it cannot find the IP and causes the key error. I will fix it in a future release but in the interim, it should still continue to work as once AWS allocates the IP, it stops raising the exception. 

Let me know if it doesn't.

**Comment by sblfc** [comment]
Hello,

I'm sorry but for amazon it just says "Pending: AWS allocating" and does not work even though the VM has been allocated in my aws dashboard and is fully up and running (just the vm and docker inside it, didn't check the proxy).

Also just as a little side note the -e DIGITALOCEAN_MIN_SCALING=0 -e DIGITALOCEAN_MAX_SCALING=0 commands do not work, it always starts at 2 but isnt important.

**Comment by sblfc** [comment]
Yeah thanks, it ended up being that, I could've sworn I did a pull.

Thanks!

**Comment by claffin** [comment]
Great, glad it's resolved!
