### ISSUE TITLE
AWS enchancements

### ISSUE THREAD

**Issue by xanrag** [claffin/cloudproxy#26]
Using the Spot market for AWS would be nice, 60-70% cheaper. Looks pretty easy, just add some InstanceMarketOptions to the create_instances call. 

Also, would be nice if the ami string was a setting since that ami doesn't exist on at least eu-west-1.

**Comment by claffin** [comment]
Thanks for the suggestion, I will add spot instance settings (as sometimes spot instances are not available) and will add a setting for the AMI in the next few days. I wasn't aware of the AMI names varied by region.
