### ISSUE TITLE
Can't change the default zone of GCP Proxies

### ISSUE THREAD

**Issue by LuongPhuHoa** [claffin/cloudproxy#56]
`docker run -e USERNAME='xxx' -e PASSWORD='xxx' -e GCP_ENABLED=True -e GCP_PROJECT='xxx' -e GCP_SIZE='e2-micro' -e GCP_ZONE='asia-northeast3-a' -e GCP_SERVICE_ACCOUNT_KEY='xxx' -it -p 8000:8000 laffin/cloudproxy:latest`

I tried this command but it always creates instances in the us default zone, I can't switch it to the different zone. Can you fix this ?

Thank you

**Comment by AlexKrois** [comment]
For anyone running into the same problem, the correct env variable would be GCP_REGION instead of GCP_ZONE :)

**Comment by claffin** [comment]
Thank you! I will update the documentation.
