### ISSUE TITLE
Issue with Hetzner provisioning

### ISSUE THREAD

**Issue by Seb3cdash** [claffin/cloudproxy#57]
Hello,

No way to provision a new proxy. Probably a change on Hetzner APIs

TypeError: __init__() got an unexpected keyword argument 'id'

**Comment by claffin** [comment]
Thanks for the info, will take a look in the next few days and fix.

**Comment by claffin** [comment]
I'm not able to replicate this issue. Please provide more info or will close.

**Comment by claffin** [comment]
Closing as issues seems resolved.
