### ISSUE TITLE
Not Working = HTTPConnectionPool(host='18.134.94.244', port=8000): Max retries exceeded with url:

### ISSUE THREAD

**Issue by muskansingh65553** [claffin/cloudproxy#64]
![image](https://user-images.githubusercontent.com/71725061/182156763-e0d455cd-dd23-464b-ad0e-7f92feadc948.png)

**Comment by claffin** [comment]
Please could you provide more information, there isn't enough information here to understand the problem.

**Comment by muskansingh65553** [comment]
I need rotating proxy to scrape google 
don't know how to do
using python + selenium
