### ISSUE TITLE
trouble authenticating proxy / documentation of authentication for AWS

### ISSUE THREAD

**Issue by EthanTheMathmo** [claffin/cloudproxy#65]
## Expected Behavior
I followed the docs here https://github.com/claffin/cloudproxy and here https://github.com/claffin/cloudproxy/blob/main/docs/aws.md
I created environment variables, all alphanumerica, for USERNAME and PASSWORD. I created an IAM role as instructed, and I can see the EC2 instances. WHen using the toy example these are correctly filled in (i.e., instead of being changeme:changeme@ip it is user:password@ip).

## Actual Behavior
WHen connecting to the proxy I get the error message:  The administrator of this proxy has not configured it to service requests from you.

---

This is almost certainly from my misunderstanding the docs (as I haven't worked with AWS before). Are we meant to set the username and password somewhere in AWS too?  I also tried creating a password for the IAM user and using that, but that isn't allowed to be alphanumeric. I'd also be happy to write some documentation for entry/beginners like myself once I get it up and running

**Comment by claffin** [comment]
This issue should be resolved now in the latest release (v0.6.5-beta). Please try again.

**Comment by claffin** [comment]
Assumed resolved now.
