### ISSUE TITLE
Unable to authenticate through DigitalOcean

### ISSUE THREAD

**Issue by HazzaWaltham123** [claffin/cloudproxy#68]
Expected Behavior

Running the command:

"docker run -e USERNAME='xxx' -e PASSWORD='xx' -e DIGITALOCEAN_ENABLED=True -e DIGITALOCEAN_ACCESS_TOKEN='xxx' -it -p 8000:8000  laffin/cloudproxy:latest

Username & Password being alphanumeric. Token validated by using:

"doctl auth init -t "xxx"

I get the following error:

  File "/usr/local/lib/python3.8/site-packages/digitalocean/baseapi.py", line 233, in get_data
    raise DataReadError(msg)
          │             └ 'Unable to authenticate you'
          └ <class 'digitalocean.DataReadError'>

I think my bug is identical to George Roscoe's. I've never had an issue running this before. I ran this a few weeks ago and it worked completely fine

**Comment by claffin** [comment]
Have you tried running a previous version? The bug George seemed to resolved itself so not sure what the issue was.

**Comment by claffin** [comment]
Not sure what the issue is. When George had the issue I failed to repeat the issue. 

Try creating a .env with your environment variables in and run the docker command with  --env-file=myenv.env. See if that works.

**Comment by HazzaWaltham123** [comment]
I have a feeling it's an environment issue. I can't replicate it on two other devices. thanks for your help though mate :)
